[workspace]
members = [
    "production/pk_trbfv",
    "production/pk_bfv",
    "production/verify_shares_trbfv",
    "production/enc_bfv",
    "production/dec_bfv",
    "production/enc_trbfv",
    "production/dec_share_trbfv",
    "production/dec_share_agg_trbfv"   
]