[workspace]
members = [
    "pk_trbfv",
    "pk_bfv",
    "verify_shares_trbfv",
    "enc_bfv",
    "dec_bfv",
    "pk_agg_trbfv",
    "enc_trbfv",
    "dec_share_trbfv",
    "dec_share_agg_trbfv"   
]