decryption_shares = [[{ coefficients = ["563594560656323", "1221103116818516", "1446315212153416", "166809412382211", "365929950533652"] }, { coefficients = ["408897622366855", "3614339080247669", "2532344127401690", "274341076406715", "4352921087457340"] }, { coefficients = ["3018346819891907", "4122081697885734", "5556516878685", "1648913678034936", "656367252199841"] }, { coefficients = ["2314896136012164", "2987961088499520", "1708261760864013", "3321048806502346", "4358087132738956"] }], [{ coefficients = ["1848361830935071", "710638402988600", "943413950535924", "268605880281749", "879692566695534"] }, { coefficients = ["434823587878817", "2957220080248307", "3150906614516755", "4419724210733040", "2126367839072338"] }, { coefficients = ["2522841479128606", "4278705322133167", "334002300894763", "3090229079307087", "3712801918689593"] }, { coefficients = ["1012678765901425", "3454330795575402", "3041266281650613", "371487389326652", "1581191730434630"] }], [{ coefficients = ["1518081546009846", "532231990840997", "1486032828508185", "1541094265882493", "509108668082764"] }, { coefficients = ["2614909706194787", "4397171869740930", "533212287836782", "3366089671113483", "3178387719460109"] }, { coefficients = ["401358198046729", "1101345769954513", "891787103861784", "2991635233067561", "1531741265410685"] }, { coefficients = ["1405372322801345", "2891214367108862", "1223101837566684", "4060256000653446", "3351387471798747"] }]]
party_ids = ["1", "2", "3"]

[params.bounds]
delta = "2056880709761530307118999640250952090321250647720126884990156"
delta_half = "1028440354880765153559499820125476045160625323860063442495078"

[params.crypto]
plaintext_modulus = "100"
q_inverse_mod_t = "21"
q_mod_t = "81"
qis = ["2251799822204929", "4503599627763713", "4503599631433729", "4503599634579457"]
t_inv_mod_q = "162493576071160894262400971579825215135378801169890023914222388"

[[crt_quotients]]
coefficients = ["8225245640173978914656543670120594810896023285", "6389727559335446132733631020349834661165292226", "8212150002115012445962624175727659081660174479", "1822605320630485501423649111899167994618850385", "4571724770457950594875296474752946231943794031"]

[[crt_quotients]]
coefficients = ["4112622835288011184801587751471775749182103748", "3194863791476536044265755636540750895808096692", "4106075016234325988911110485604861501595912671", "911302663683587514081889524267035708864236969", "2285862393677949420268747234688721074782037989"]

[[crt_quotients]]
coefficients = ["4112622831936605011365305309383077894863278817", "3194863788873018371268963930781592579444088965", "4106075012888255680706809009630152553258542836", "911302662940960364630627349408665539401616883", "2285862391815183578464627579413536681442586871"]

[[crt_quotients]]
coefficients = ["4112622829063971152767362095456932798422184160", "3194863786641431797791852338604069830275727419", "4106075010020195420872213514595636860676526526", "911302662304422808921452330968249110071168490", "2285862390218527145048903560598901349814634755"]

[message]
coefficients = ["9", "7", "9", "2", "5"]

[u_global]
coefficients = ["18521606670135633132850571552514432951483932269840345805355225", "14388387382049492518987232345572406339110706616426352074912699", "18492117914682792337129849123095114050266757804989617424962723", "4104142336945484865630838580086251561083208853992582722731544", "10294609025287082993510164071503111450341252632596092890780846"]
