decryption_shares = [[{ coefficients = ["4243523492"] }, { coefficients = ["22071717434"] }], [{ coefficients = ["5154735895"] }, { coefficients = ["66632267397"] }], [{ coefficients = ["43965114989"] }, { coefficients = ["9986870105"] }]]
party_ids = ["1", "2", "3"]

[params.bounds]
delta = "472234452797701980979"
delta_half = "236117226398850990489"

[params.crypto]
plaintext_modulus = "10"
q_inverse_mod_t = "7"
qis = ["68719403009", "68719230977"]

[[crt_quotients]]
coefficients = ["54975384781"]

[[crt_quotients]]
coefficients = ["54975522407"]

[message]
coefficients = ["8"]

[u_global]
coefficients = ["3777875622381615683809"]
