decryption_shares = [[{ coefficients = ["1707608032134766"] }, { coefficients = ["423703388121388"] }, { coefficients = ["3786368429444019"] }, { coefficients = ["2630806202276421"] }], [{ coefficients = ["1569882857122977"] }, { coefficients = ["524894592086590"] }, { coefficients = ["3156983607396708"] }, { coefficients = ["112911074082329"] }], [{ coefficients = ["1469727469545490"] }, { coefficients = ["350587305827153"] }, { coefficients = ["1288777142560105"] }, { coefficients = ["748040976895466"] }]]
party_ids = ["1", "2", "3"]

[params.bounds]
delta = "2056880709761530307118999640250952090321250647720126884990156"
delta_half = "1028440354880765153559499820125476045160625323860063442495078"

[params.crypto]
plaintext_modulus = "100"
qis = ["2251799822204929", "4503599627763713", "4503599631433729", "4503599634579457"]
q_mod_t = "81"
t_inv_mod_q = "162493576071160894262400971579825215135378801169890023914222388"

[[crt_quotients]]
coefficients = ["35631938263034724673270938479127771389750731113"]

[[crt_quotients]]
coefficients = ["17815969197368510305138199934168703224284812999"]

[[crt_quotients]]
coefficients = ["17815969182850147803844053286100850800642435724"]

[[crt_quotients]]
coefficients = ["17815969170405837107282280093765354965830333557"]

[message]
coefficients = ["39"]

[u_global]
coefficients = ["80235992245518599675395950517641606482286564009636392456836834"]
