decryption_shares = [[{ coefficients = ["61558745876", "21124282711", "31867020530", "35095831734", "39935985069"] }, { coefficients = ["45114273558", "36057756721", "46310067006", "18825231745", "30527512724"] }], [{ coefficients = ["55226237248", "46965540362", "28476163364", "57545622224", "7258770999"] }, { coefficients = ["11635932818", "4081704183", "33137053930", "58851689120", "34112755570"] }], [{ coefficients = ["1613015491", "1922848057", "10425113554", "26121723306", "5058451789"] }, { coefficients = ["43870083304", "62116492047", "36053978996", "37620288594", "45126333512"] }]]
party_ids = ["1", "2", "3"]

[params.bounds]
delta = "472234452797701980979"
delta_half = "236117226398850990489"

[params.crypto]
plaintext_modulus = "10"
q_inverse_mod_t = "7"
q_mod_t = "3"
qis = ["68719403009", "68719230977"]
t_inv_mod_q = "1416703358393105942938"

[[crt_quotients]]
coefficients = ["61847307879", "48103461683", "61847307879", "13743846195", "34359615488"]

[[crt_quotients]]
coefficients = ["61847462708", "48103582106", "61847462708", "13743880601", "34359701504"]

[message]
coefficients = ["9", "7", "9", "2", "5"]

[u_global]
coefficients = ["4250110075179312549286", "3305641169583904285269", "4250110075179299692963", "944468905595407955600", "2361172263988520894382"]
