decryption_shares = [[{ coefficients = ["44025878689", "31310604440", "39684457330", "19340524782", "64111789219"] }, { coefficients = ["2458710273", "29694132462", "34782635434", "26495463450", "3867826523"] }], [{ coefficients = ["31512915628", "9640994044", "67443486744", "41786782756", "30826525585"] }, { coefficients = ["53294879957", "32503077916", "18626069474", "29179635107", "18897094047"] }], [{ coefficients = ["51803395158", "65573335646", "35172707297", "26143362249", "3210134015"] }, { coefficients = ["21949030625", "29057906772", "27120657356", "63064129885", "10715007487"] }]]
party_ids = ["1", "2", "3"]

[params.bounds]
delta = "472234452797701980979"
delta_half = "236117226398850990489"

[params.crypto]
plaintext_modulus = "10"
q_inverse_mod_t = "7"
q_mod_t = "3"
qis = ["68719403009", "68719230977"]
t_inv_mod_q = "1416703358393105942938"

[[crt_quotients]]
coefficients = ["61847307879", "48103461683", "61847307879", "13743846195", "34359615488"]

[[crt_quotients]]
coefficients = ["61847462708", "48103582106", "61847462708", "13743880601", "34359701504"]

[message]
coefficients = ["9", "7", "9", "2", "5"]

[u_global]
coefficients = ["4250110075179324889243", "3305641169583929167972", "4250110075179317029975", "944468905595440192091", "2361172263988496725300"]
