decryption_shares = [[{ coefficients = ["450908627324241"] }, { coefficients = ["2130958053763692"] }, { coefficients = ["1715282853554546"] }, { coefficients = ["2664285029351502"] }], [{ coefficients = ["422012256014128"] }, { coefficients = ["287633635762351"] }, { coefficients = ["2553767094792519"] }, { coefficients = ["3924831913359248"] }], [{ coefficients = ["1497229521213940"] }, { coefficients = ["2489651120470599"] }, { coefficients = ["4274229508308798"] }, { coefficients = ["1668059840838759"] }]]
party_ids = ["1", "2", "3"]

[params.bounds]
delta = "2056880709761530307118999640250952090321250647720126884990156"
delta_half = "1028440354880765153559499820125476045160625323860063442495078"

[params.crypto]
plaintext_modulus = "100"
q_inverse_mod_t = "21"
qis = ["2251799822204929", "4503599627763713", "4503599631433729", "4503599634579457"]

[[crt_quotients]]
coefficients = ["49326530799259078202041807872315787385641051075"]

[[crt_quotients]]
coefficients = ["24663265490789572396337666260487254964293623965"]

[[crt_quotients]]
coefficients = ["24663265470691298488576885763172572371823939675"]

[[crt_quotients]]
coefficients = ["24663265453464206593710540718134667477711675768"]

[message]
coefficients = ["54"]

[u_global]
coefficients = ["111073473283757546657403186640305114408242166161313862240892954"]