decryption_shares = [[{ coefficients = ["37303775508", "31787868007", "35125321321", "49105573024", "38593752509"] }, { coefficients = ["54223915501", "48717243443", "4873940897", "57135033749", "56987777113"] }], [{ coefficients = ["2546855331", "2051457802", "63489613428", "9150846671", "41491188273"] }, { coefficients = ["28574687729", "4971607806", "1962851737", "54781572544", "9211497711"] }], [{ coefficients = ["53789299311", "41346894592", "36961373297", "45075750106", "43060642499"] }, { coefficients = ["67368134657", "26806583826", "66829965677", "47928363110", "28477872939"] }]]
party_ids = ["1", "2", "3"]

[params.bounds]
delta = "472234452797701980979"
delta_half = "236117226398850990489"

[params.crypto]
plaintext_modulus = "10"
q_inverse_mod_t = "7"
qis = ["68719403009", "68719230977"]

[[crt_quotients]]
coefficients = ["61847307879", "48103461683", "61847307879", "13743846195", "34359615488"]

[[crt_quotients]]
coefficients = ["61847462708", "48103582106", "61847462708", "13743880601", "34359701504"]

[message]
coefficients = ["9", "7", "9", "2", "5"]

[u_global]
coefficients = ["4250110075179323261735", "3305641169583903126345", "4250110075179289907896", "944468905595417323902", "2361172263988518538599"]
