decryption_shares = [[{ coefficients = ["7543765632", "28440765284", "58979287835", "19909785135", "58604238497"] }, { coefficients = ["41270173929", "21096921341", "132223771", "22049165403", "18660470173"] }], [{ coefficients = ["4370850198", "39259618044", "7302382755", "50220172804", "68085510178"] }, { coefficients = ["26839384088", "11839965465", "23317423943", "53228978047", "18024066457"] }], [{ coefficients = ["11090087029", "25605505088", "3007944716", "49708062590", "62791631349"] }, { coefficients = ["32291796980", "61585019751", "7692325672", "11084902148", "32438519142"] }]]
party_ids = ["1", "2", "3"]

[params.bounds]
delta = "472234452797701980979"
delta_half = "236117226398850990489"

[params.crypto]
plaintext_modulus = "10"
q_inverse_mod_t = "7"
q_mod_t = "3"
qis = ["68719403009", "68719230977"]
t_inv_mod_q = "1416703358393105942938"

[[crt_quotients]]
coefficients = ["61847307879", "48103461683", "61847307879", "13743846195", "34359615488"]

[[crt_quotients]]
coefficients = ["61847462708", "48103582106", "61847462708", "13743880601", "34359701504"]

[message]
coefficients = ["9", "7", "9", "2", "5"]

[u_global]
coefficients = ["4250110075179310841242", "3305641169583934753964", "4250110075179301861849", "944468905595412503347", "2361172263988498019698"]
