[package]
name = "enc_bfv_recursion"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
circuits = { path = "../../circuits" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20251104", directory = "barretenberg/noir/bb_proof_verification" }
