name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  rust:
    name: Rust CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crates
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.85.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0
          components: rustfmt
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: crates -> target

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo build --release

  noir:
    name: Noir CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: circuits
    steps:
      - uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: v1.0.0-beta.11

      - name: Check Noir formatting
        run: nargo fmt --check

      - name: Build Noir project
        run: nargo check

      - name: Run Noir tests
        run: nargo test

  noir-examples:
    name: Noir Example
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: examples
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.85.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0
          override: true

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: v1.0.0-beta.11

      - name: Install bbup (Barretenberg)
        run: |
          curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/next/barretenberg/bbup/install | bash
          echo "$HOME/.bb" >> $GITHUB_PATH
          export PATH="$HOME/.bb:$PATH"
          bbup
          bb --version

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 15G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Compile example circuit
        working-directory: examples/sks_circuit
        run: nargo compile

      - name: Execute example circuit
        working-directory: examples/sks_circuit
        run: nargo execute

      - name: Generate proof
        working-directory: examples/sks_circuit
        run: bb prove -b ./target/sks_circuit.json -w ./target/sks_circuit.gz -o ./target

      - name: Generate verification key
        working-directory: examples/sks_circuit
        run: bb write_vk -b ./target/sks_circuit.json -o ./target

      - name: Verify proof
        working-directory: examples/sks_circuit
        run: bb verify -k ./target/vk -p ./target/proof
        continue-on-error: false